frame_id: map
locations:
  microwave:
    frame_id: map
    position:
      x: 0.038917
      y: 0.002067
      z: 0.0
    orientation:
      x: -0.0
      y: 0.0
      z: -0.005742
      w: 0.999984
  fridge:
    frame_id: map
    position:
      x: -1.346928
      y: -0.065874
      z: -0.0
    orientation:
      x: 0.0
      y: -0.0
      z: -0.003174
      w: 0.999995
  sink:
    frame_id: map
    position:
      x: 1.430202
      y: -0.087815
      z: 0.0
    orientation:
      x: 0.0
      y: -0.0
      z: -0.03681
      w: 0.999322
  table:
    frame_id: map
    position:
      x: 0.723227
      y: -4.337563
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.725902
      w: 0.687798
  kitchen_exit:
    frame_id: map
    position:
      x: -1.550127
      y: 0.001019
      z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.514721
      w: 0.857358
  kitchen_enter:
    frame_id: map
    position:
      x: -1.693239
      y: -0.351025
      z: 0.0
    orientation:
      x: 0.0
      y: -0.0
      z: 0.544067
      w: 0.839042
  movable_table:
    frame_id: map
    position:
      x: -0.369539
      y: -4.293008
      z: -0.0
    orientation:
      x: -0.0
      y: -0.0
      z: -0.714092
      w: 0.700052
  dining_table:
    frame_id: map
    position:
      x: 0.028225
      y: -3.855209
      z: -0.0
    orientation:
      x: 0.0
      y: -0.0
      z: 0.703817
      w: 0.710381
  start:
    frame_id: map
    position:
      x: 0.621637
      y: -3.89946
      z: 0.0
    orientation:
      x: 0.0
      y: -0.0
      z: -0.999951
      w: -0.009882
