from pathlib import Path
from typing import List

from feeding_deployment.preference_learning.config.affective_state import AFFECTIVE_STATES
from feeding_deployment.preference_learning.config.mealtime_context import SETTINGS, TIMES_OF_DAY, MEAL_CONTENTS
from feeding_deployment.preference_learning.config.physical_capabilities import PHYSICAL_CAPABILITY_PROFILES
from feeding_deployment.preference_learning.data_generation.prompts.system_description import get_system_description_prompt

PREFERENCE_GENERATION_PROMPT_PATH = Path(__file__).parent / "preference_generation.txt"

def get_preference_generation_prompt(
    physical_profile_label: str, 
    user_preference_encoding: str,
    meal: str,
    dippable_items: str,
    sauces: str,
    storage_condition: str,
    intended_serving_temp: str,
    setting: str,
    time_of_day: str,
    affective_state: str,  
) -> str:
    template = PREFERENCE_GENERATION_PROMPT_PATH.read_text(encoding="utf-8")
    system_description = get_system_description_prompt()
    
    PHYSICAL_CAPABILITY_BY_LABEL = {p.label: p for p in PHYSICAL_CAPABILITY_PROFILES}
    physical_profile_description = PHYSICAL_CAPABILITY_BY_LABEL[physical_profile_label].description

    return template.format(
        system_description=system_description,
        physical_profile=physical_profile_description,
        user_preference_encoding=user_preference_encoding,
        meal=meal,
        dippable_items=dippable_items,
        sauces=sauces,
        storage_condition=storage_condition,
        intended_serving_temp=intended_serving_temp,
        setting=setting,
        time_of_day=time_of_day,
        affective_state=affective_state
    )
    
if __name__ == "__main__":
    physical_profile = PHYSICAL_CAPABILITY_PROFILES[0]  # just take the first one as an example
    meal_contents = MEAL_CONTENTS[0]  # just take the first meal as an example
    setting = SETTINGS[0]  # just take the first setting as an example
    time_of_day = TIMES_OF_DAY[0]  # just take the first time of day as an example
    affective_state = AFFECTIVE_STATES[0]  # just take the first affective state as an example
    
    user_preference_encoding = "PLACEHOLDER_USER_PREFERENCE_ENCODING"  # in actual generation, this will be generated by the user preference encoding model based on the physical profile

    prompt = get_preference_generation_prompt(
        physical_profile_label=physical_profile.label,
        user_preference_encoding=user_preference_encoding,
        meal=meal_contents.label,
        dippable_items=", ".join(meal_contents.dippable_items) if meal_contents.dippable_items else "None",
        sauces=", ".join(meal_contents.sauces) if meal_contents.sauces else "None",
        storage_condition=meal_contents.storage_condition,
        intended_serving_temp=meal_contents.intended_serving_temp,
        setting=setting,
        time_of_day=time_of_day,
        affective_state=affective_state
    )
    
    print(prompt)